services:
  - type: web
    plan: free
    name: file sharing
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    repo: https://github.com/Sksathaa/File-Sharing-Bot/tree/main.git      
    branch: main
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH
        sync: false
      - key: ADMINS
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_URI
        sync: false 
      - key: PICS
        sync: false
      - key: LOG_CHANNEL
        sync: false    
    autoDeploy: trueï¿¼Enter
